name: CI
on: [pull_request, push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Prettier check
        run: yarn format:check
